name: flutter_revue
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/


